server:
  port: 8083

spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/account-service-database

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost