server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/v1/accounts/**, /api/v1/customers/**
        - id: credit-service
          uri: lb://CREDIT-SERVICE
          predicates:
            - Path=/api/v1/credits/**
        - id: movement-service
          uri: lb://MOVEMENT-SERVICE
          predicates:
            - Path=/api/v1/movements/**, /api/v1/products/**