server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  #instance:
  #  hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    #discovery:
    #  enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://localhost:8082/
          predicates:
            - Path=/api/v1/customers/**
        - id: account-service
          uri: lb://account-service/
          predicates:
            - Path=/api/v1/accounts/**, /api/v1/customers/**
        - id: credit-service
          uri: lb://credit-service/
          predicates:
            - Path=/api/v1/credits/**
        - id: movement-service
          uri: lb://movement-service/
          predicates:
            - Path=/api/v1/movements/**, /api/v1/products/**