server:
  port: 8087

spring:
  application:
    name: card-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/card-service-database

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost