server:
  port: 8084

spring:
  application:
    name: credit-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/credit-service-database

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost