server:
  port: 8085

spring:
  application:
    name: movement-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/movement-service-database

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost